version: "3"
services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.4.44-17.0
    environment:
      LDAP_URLS: "ldap:/// ldaps:///"
    ports:
      - "389:389"
      - "636:636"
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/ldap:/var/lib/ldap
      - /var/local/dcm4chee-arc/slapd.d:/etc/ldap/slapd.d
